"""tablas iniciales

Revision ID: fffa41eda095
Revises: 
Create Date: 2026-03-05 09:29:35.756208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffa41eda095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('piso', sa.String(length=10), nullable=True),
    sa.Column('departamento', sa.String(length=10), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('tipo_cuenta', sa.String(length=50), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=False),
    sa.Column('saldo_dolar', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dni'], ['clientes.dni'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('detalle', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dni'], ['clientes.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('monto_solicitado', sa.Float(), nullable=False),
    sa.Column('monto_cuota', sa.Float(), nullable=False),
    sa.Column('cuotas_totales', sa.Integer(), nullable=False),
    sa.Column('cuotas_pagas', sa.Integer(), nullable=False),
    sa.Column('tasa_interes', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('fecha_solicitud', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_fin', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dni'], ['clientes.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarjetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('fecha_vencimiento', sa.String(length=10), nullable=False),
    sa.Column('cvv', sa.String(length=3), nullable=False),
    sa.Column('consumos', sa.Float(), nullable=False),
    sa.Column('limite', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dni'], ['clientes.dni'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni_origen', sa.Integer(), nullable=False),
    sa.Column('dni_destino', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dni_destino'], ['clientes.dni'], ),
    sa.ForeignKeyConstraint(['dni_origen'], ['clientes.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras_tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('tarjeta_id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=200), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('importe_cuota', sa.Float(), nullable=False),
    sa.Column('cuotas_totales', sa.Integer(), nullable=False),
    sa.Column('cuota_actual', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['dni'], ['clientes.dni'], ),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('cuota_nro', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_prestamo')
    op.drop_table('compras_tarjeta')
    op.drop_table('transferencias')
    op.drop_table('tarjetas')
    op.drop_table('prestamos')
    op.drop_table('movimientos')
    op.drop_table('cuentas')
    op.drop_table('usuarios')
    op.drop_table('empleados')
    op.drop_table('clientes')
    # ### end Alembic commands ###
